# Generated by Django 2.2.5 on 2019-11-22 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0003_auto_20191122_2109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collaborator',
            name='team',
        ),
        migrations.CreateModel(
            name='ApplicationMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.PositiveSmallIntegerField()),
                ('application', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='organisation.Application')),
                ('collaborator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='organisation.Collaborator')),
            ],
        ),
    ]
