# Generated by Django 2.2.5 on 2019-11-23 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0004_auto_20191122_2133'),
    ]

    operations = [
        migrations.AddField(
            model_name='direction',
            name='shorname',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
