# Generated by Django 2.2.5 on 2019-11-23 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0006_application_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='role',
        ),
        migrations.AddField(
            model_name='applicationmember',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='organisation.Role'),
        ),
    ]
