# Generated by Django 2.2.5 on 2019-11-23 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0007_auto_20191123_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaborator',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='applicationmember',
            name='collaborator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='member', to='organisation.Collaborator'),
        ),
    ]
