# Generated by Django 2.2.5 on 2019-12-30 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0008_auto_20191123_1540'),
    ]

    operations = [
        migrations.RenameField(
            model_name='direction',
            old_name='shorname',
            new_name='shortname',
        ),
        migrations.CreateModel(
            name='ProjectRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('request_date', models.DateField(blank=True, null=True)),
                ('affected', models.BooleanField(default=False)),
                ('affectation_date', models.DateField(blank=True, null=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organisation.Project')),
                ('role', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='organisation.Role')),
            ],
        ),
    ]
