# Generated by Django 2.2.5 on 2020-06-19 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
