# Generated by Django 2.2.5 on 2020-06-18 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usercomments', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comments',
            new_name='Comment',
        ),
    ]
