# Generated by Django 2.2.5 on 2020-07-01 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usercomments', '0004_auto_20200629_1406'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='name',
            new_name='title',
        ),
    ]
